yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="home_page"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit")
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("logout/", LogoutView.as_view(template_name="users/logged_out.html"),
         name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="users/login.html"),
         name="login"),
    path("password_change/", PasswordChangeView.as_view(
         template_name="users/password_change_form.html"),
         name="password_change"),
    path("password_change_done/", PasswordChangeDoneView.as_view(
         template_name="users/password_change_done.html"),
         name="password_change_done"),
    path("password_reset/", PasswordResetView.as_view(
         template_name="users/password_reset_form.html"),
         name="password_reset"),
    path("password_reset_done/", PasswordResetDoneView.as_view(
         template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(
         template_name="users/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(
         template_name="users/password_reset_complete.html"),
         name="password_reset_complete")
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="name")
    slug = models.SlugField(unique=True, blank=True, null=True, default=None,
                            verbose_name="slug")
    description = models.TextField(verbose_name="description")

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="name")
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="author"
    )
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name="posts")

    class Meta:
        ordering = ["-pub_date"]

yatube/posts/forms.py
from django import forms
from .models import Post
from .models import Group


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea,
                           label="Текст",
                           help_text="Текст вашего поста")
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   required=False,
                                   label="Группа, к которой относится пост",
                                   help_text="Выберите группу")

    class Meta:
        model = Post
        fields = ("text", "group")

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = "about/author.html"


class AboutTechView(TemplateView):
    template_name = "about/tech.html"

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .utils import paginate_page

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    page_obj = paginate_page(request, post_list)
    context = {
        "page_obj": page_obj
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginate_page(request, post_list)
    title = group.title
    description = group.description
    context = {
        "page_obj": page_obj,
        "title": title,
        "description": description
    }

    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related("author")
    template = "posts/profile.html"
    page_obj = paginate_page(request, post_list)
    context = {
        "page_obj": page_obj,
        "author": author
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {
        "post": post
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            author = request.user.username
            return redirect("posts:profile", author)
        context = {
            "form": form
        }
        return render(request, "posts/create_post.html", context)
    form = PostForm()
    context = {
        "form": form
    }
    return render(request, "posts/create_post.html", context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, instance=post)
    is_edit = True
    context = {
        "form": form,
        "is_edit": is_edit,
        "id": post_id,
    }
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("posts:post_detail", post_id=post_id)
        return render(request, "posts/create_post.html", context)
    return render(request, "posts/create_post.html", context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!-- templates/posts/index.html -->
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="img/fav/fav.ico" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"> 
  <title>{% block title %}Главная страница{% endblock %}</title>
</head>
  <body>       
    <header>
      {% include "includes/header.html" %}
    </header>
    <main>
      <div class="container py-5"> 
        {% block content %}Тут что-то есть.{% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:home_page" %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">              
        <a class="nav-link {% if view_name  == "about:author" %}active{% endif %}" 
          href="{% url "about:author" %}"
        >
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == "about:tech" %}active{% endif %}" 
          href="{% url "about:tech" %}"
        >
          Технологии
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == "posts:post_create" %}active{% endif %}" 
          href="{% url "posts:post_create" %}"
        >
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link {% if view_name == "users:password_change" %}active{% endif %}" 
          href="{% url "users:password_change" %}"
        >
          Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url "users:logout" %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url "users:login" %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url "users:signup" %}">Регистрация</a>
      {% endif %}
      </li>
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/posts/create_post.html
<!DOCTYPE html>
{% extends "base.html" %}
<title>
  {% block title %}Новая запись{% endblock %}
</title>
{% block content %} 
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          Новый пост             
        </div>
        <div class="card-body">
          {% if is_edit %}
          <form method="post" action="{% url "posts:post_edit" id %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                {{ form.text.label }}                
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text }}
              </textarea>                
              <small id="id_text-help" class="form-text text-muted">
                {{ form.text.help_text }}
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  {{ form.group.label }}
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                  Сохранить       
              </button> 
            </div>
          </form>
          {% else %}
          <form method="post" action="{% url "posts:post_create" %}">
            {% csrf_token %}         
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text }}               
              <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  {{ form.group.label }}
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                  Добавить            
              </button> 
            </div>
          </form>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
<title>
  {% block title %}{{ title }}{% endblock %}
</title>
{% block content %}  
<h1>{{ title }}</h1>
<p>{{ description }}</p>
{% for post in page_obj %}

<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>      
  <p>
    {{ post.text }}
  </p>         
</article>
<hr>
{% endfor %}
{% if not forloop.last %}<hr>{% endif %}
{% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends "base.html" %}
<title>
  {% block title %}Главная страница{% endblock %}
</title>
{% block content %} 
<h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}   
  <a href="{% url "posts:group_posts" post.group.slug %}">все записи группы</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include "posts/includes/paginator.html" %}
{% endblock %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
<title>
  {% block title %}Информация о посте{% endblock %}
</title>
{% block content %} 
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
      Всего постов автора:  <span >{{ post.author.posts.count }}</span>
     </li>
      {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url "posts:group_posts" post.group.slug %}">
            все записи группы
          </a>
        </li>
      {% endif %}
      <li class="list-group-item">
        <a href="{% url "posts:profile" post.author %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
      {{ post.text }} 
    </p>
  </article>
</div> 
{% endblock %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
<title>
  {% block title %}Профайл пользователя {{ author }}{% endblock %}
</title>
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% for post in page_obj %}  
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url "posts:profile" post.author %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      {{ post.text }}
    </p>
    <a href="{% url "posts:post_detail" post.id %}">подробная информация </a>
  </article>
  {% endfor %}
  {% if post.group %}
    <a href="{% url "posts:group_posts" post.author %}">все записи группы</a>
  {% endif %}    
  <hr>
  {% if not forloop.last %}<hr>{% endif %} 
  {% include "posts/includes/paginator.html" %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
# templates/users/login.html

{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url "users:password_reset" %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="../users/password_change_form.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="../users/login.html">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5">
  {% if validlink %} 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post" action="../users/lpassword_reset_confirm.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль        
                <span class="required text-danger">*</span>        
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
              </small>      
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля        
                <span class="required text-danger">*</span>        
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
  {% endif %}
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
<title>
  {% block title %}Профиль пользователя{% endblock %}
</title>
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="../users/password_reset_form.html">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>    
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->

{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}

  <form method="post" action="{% url "users:signup" %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
  </form>

{% endblock %} 